spring:
  application:
    name: customer-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      username: admin
      password: admin
  rabbitmq:
    host: http://localhost:5672
    username: admin
    password: password
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://rtr-eureka-server:8761/eureka/