service:
  info: Account Service Microservice [Dev]

spring:
  application:
    name: account-service
  security:
    oauth2:
      resourceserver:   
        jwt:
          issuer-uri: http://localhost:8080/realms/[keycloak-realm]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

server:
  port: 16801
