eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: config-server
  profiles:
    active: git,vault
  cloud:
    config:
      server:
        vault:
          host: [host_to_vault]
          authentication: TOKEN
          token: [token]
          kv-version: 2
          backend: secret
          profile-separator: /
          scheme: https
          port: 443
        git:
          uri: https://github.com/[git_username]/rtr-config-files.git
          search-paths: "services/**"
          default-label: main
          clone-on-start: true
          force-pull: true
          username: [git_username]
          password: [token]

server:
  port: 8888
encrypt:
  key: "test"
