spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      server:
        vault:
          host: rtr-vault
eureka:
  client:
    service-url:
      defaultZone: http://rtr-eureka-server:8761/eureka/